# fly.toml file generated for fakebookcr on 2023-04-03T11:02:15-05:00

app = "fakebookcr"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "ord"
processes = []

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[mounts]
  source="fakebookcr_data"
  destination="/data"
